<?php
echo "<?php\n";
echo "?>\n";
echo "<!DOCTYPE html>\n";
echo "<html lang=\"es\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n";
echo "    <title>Bienvenidos al Baloncesto</title>\n";
echo "    <link rel=\"stylesheet\" href=\"estilos.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "    \n";
echo "    <header>\n";
echo "        <img src=\"nba.png\" alt=\"Logo de Baloncesto\">\n";
echo "        <h1>Bienvenidos al Mundo del Baloncesto</h1>\n";
echo "        <nav>\n";
echo "            <ul>\n";
echo "                <li><a href=\"index.php\">Inicio</a></li>\n";
echo "                <li><a href=\"pag1.php\">Jugadores</a></li>\n";
echo "                <li><a href=\"pag2.php\">Equipos</a></li>\n";
echo "            </ul>\n";
echo "        </nav>\n";
echo "    </header>\n";
echo "   \n";
echo "    <section>\n";
echo "        <h2>¿Qué es el Baloncesto?</h2>\n";
echo "        <p>El baloncesto es un deporte dinámico, emocionante y lleno de acción. Jugado entre dos equipos de cinco jugadores cada uno, el objetivo es encestar un balón en la canasta del equipo contrario. En esta web exploraremos los jugadores más famosos y los equipos más exitosos en la historia del baloncesto.</p>\n";
echo "    </section>\n";
echo "    <section class=\"container\">\n";
echo "        <div class=\"box\">\n";
echo "            <h3>Jugadores Famosos</h3>\n";
echo "            <img src=\"michael.png\" alt=\"Michael Jordan\">\n";
echo "            <p>Conoce a los jugadores más emblemáticos de la historia, como Michael Jordan, LeBron James y Kobe Bryant. Estos íconos del baloncesto dejaron una huella imborrable en el deporte.</p>\n";
echo "            <ul>\n";
echo "                <li><a href=\"pag1.php\">Ver más sobre los jugadores</a></li>\n";
echo "            </ul>\n";
echo "        </div>\n";
echo "        \n";
echo "        <div class=\"box\">\n";
echo "            <h3>Equipos Icónicos</h3>\n";
echo "            <img src=\"lakers.png\" alt=\"Los Angeles Lakers\">\n";
echo "            <p>Los equipos más exitosos, como Los Angeles Lakers y Chicago Bulls, han sido casa de leyendas del baloncesto. Descubre su historia, logros y los jugadores que los hicieron grandes.</p>\n";
echo "            <ul>\n";
echo "                <li><a href=\"pag2.php\">Ver más sobre los equipos</a></li>\n";
echo "            </ul>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "    <section>\n";
echo "        <h2>Últimas Noticias</h2>\n";
echo "        <p>La NBA ha arrancado una nueva temporada, y los equipos están más competitivos que nunca. Grandes jugadores como LeBron James y Giannis Antetokounmpo se preparan para luchar por el campeonato. ¿Quién será el próximo campeón?</p>\n";
echo "    </section>\n";
echo "    <footer>\n";
echo "        <p>&copy; 2024 Baloncesto Web. Todos los derechos reservados.</p>\n";
echo "    </footer>\n";
echo "</body>\n";
echo "</html>\n";
echo "<?php\n";
echo "?>\n";
echo "\n";
?>