<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"es\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n";
echo "    <title>Jugadores de Baloncesto</title>\n";
echo "    <link rel=\"stylesheet\" href=\"estilos.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "    <header>\n";
echo "        <img src=\"nba.png\" alt=\"Logo de Baloncesto\">\n";
echo "        <h1>Jugadores Famosos de Baloncesto</h1>\n";
echo "        <nav>\n";
echo "            <ul>\n";
echo "                <li><a href=\"index.html\">Inicio</a></li>\n";
echo "                <li><a href=\"pag1.html\">Jugadores</a></li>\n";
echo "                <li><a href=\"pag2.html\">Equipos</a></li>\n";
echo "            </ul>\n";
echo "        </nav>\n";
echo "    </header>\n";
echo "    <section>\n";
echo "        <h2>Jugadores Legendarios</h2>\n";
echo "        <div class=\"container\">\n";
echo "            <div class=\"box\">\n";
echo "                <h3>Michael Jordan</h3>\n";
echo "                <img src=\"michael.png\" alt=\"Michael Jordan\">\n";
echo "                <p>Considerado el mejor jugador de baloncesto de todos los tiempos. Michael Jordan ganó 6 campeonatos de la NBA con los Chicago Bulls y se llevó 5 premios MVP.</p>\n";
echo "                <ul>\n";
echo "                    <li><a href=\"#\">Ver más sobre Jordan</a></li>\n";
echo "                </ul>\n";
echo "            </div>\n";
echo "            <div class=\"box\">\n";
echo "                <h3>LeBron James</h3>\n";
echo "                <img src=\"lebron.png\" alt=\"LeBron James\">\n";
echo "                <p>LeBron James ha ganado 4 campeonatos de la NBA y es conocido por su increíble versatilidad en el campo. Juega para Los Angeles Lakers.</p>\n";
echo "                <ul>\n";
echo "                    <li><a href=\"#\">Ver más sobre LeBron</a></li>\n";
echo "                </ul>\n";
echo "            </div>\n";
echo "            <div class=\"box\">\n";
echo "                <h3>Kobe Bryant</h3>\n";
echo "                <img src=\"kobe.png\" alt=\"Kobe Bryant\">\n";
echo "                <p>Kobe Bryant, conocido como \"The Black Mamba\", ganó 5 campeonatos con Los Angeles Lakers y es considerado uno de los jugadores más icónicos de la historia.</p>\n";
echo "                <ul>\n";
echo "                    <li><a href=\"#\">Ver más sobre Kobe</a></li>\n";
echo "                </ul>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "    <footer>\n";
echo "        <p>&copy; 2024 Baloncesto Web. Todos los derechos reservados.</p>\n";
echo "    </footer>\n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
?>