<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"es\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n";
echo "    <title>Equipos de Baloncesto</title>\n";
echo "    <link rel=\"stylesheet\" href=\"estilos.css\">\n";
echo "</head>\n";
echo "<body>\n";
echo "    <header>\n";
echo "        <img src=\"nba.png\" alt=\"Logo de Baloncesto\">\n";
echo "        <h1>Equipos Famosos de Baloncesto</h1>\n";
echo "        <nav>\n";
echo "            <ul>\n";
echo "                <li><a href=\"index.html\">Inicio</a></li>\n";
echo "                <li><a href=\"pag1.html\">Jugadores</a></li>\n";
echo "                <li><a href=\"pag2.html\">Equipos</a></li>\n";
echo "            </ul>\n";
echo "        </nav>\n";
echo "    </header>\n";
echo "    <section>\n";
echo "        <h2>Equipos Icónicos</h2>\n";
echo "        <div class=\"container\">\n";
echo "            <div class=\"box\">\n";
echo "                <h3>Los Angeles Lakers</h3>\n";
echo "                <img src=\"lakers.png\" alt=\"Los Angeles Lakers\">\n";
echo "                <p>Los Lakers son uno de los equipos más exitosos de la NBA, con múltiples campeonatos. Han sido hogar de leyendas como Kobe Bryant y Magic Johnson.</p>\n";
echo "                <ul>\n";
echo "                    <li><a href=\"#\">Ver más sobre los Lakers</a></li>\n";
echo "                </ul>\n";
echo "            </div>\n";
echo "            <div class=\"box\">\n";
echo "                <h3>Chicago Bulls</h3>\n";
echo "                <img src=\"bulls.png\" alt=\"Chicago Bulls\">\n";
echo "                <p>Los Bulls, con su emblema de toro, son famosos por la era dorada de Michael Jordan. Ganaron 6 campeonatos durante la década de los 90.</p>\n";
echo "                <ul>\n";
echo "                    <li><a href=\"#\">Ver más sobre los Bulls</a></li>\n";
echo "                </ul>\n";
echo "            </div>\n";
echo "            <div class=\"box\">\n";
echo "                <h3>Boston Celtics</h3>\n";
echo "                <img src=\"celtics.png\" alt=\"Boston Celtics\">\n";
echo "                <p>Los Celtics son uno de los equipos más históricos de la NBA, con 17 campeonatos en su haber. Son conocidos por su legado y su rivalidad con los Lakers.</p>\n";
echo "                <ul>\n";
echo "                    <li><a href=\"#\">Ver más sobre los Celtics</a></li>\n";
echo "                </ul>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "    <footer>\n";
echo "        <p>&copy; 2024 Baloncesto Web. Todos los derechos reservados.</p>\n";
echo "    </footer>\n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
?>